### PR TITLE
Fix backoffice "unexpected token" error with Spanish language

### PR DESCRIPTION
**Pull request by drkbcn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Addon installation is broken when the BO is in Spanish due an unexpected token error caused by a new line character.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26028
| How to test?      | Change language to Spanish (Spain) and try to upload a module.

### CODE REVIEW

**Comment by matks** [comment]
> After reading some previous PR, I'd noticed that I should make the changes on Crowdin, so I requested access there. Feel free to close this PR if this isn't the right place.

I think we can merge your PR to "hotfix" 1.7.8.0 shops and also mirror your change in Crowdin.

Better wait for Monday with the translation experts to make sure the above idea is not going to destroy everything 😅

Great finding and great bugfix by the way !

We'll also have to create a test or a validation check to make sure this does not happen again. A basic XML validation step should do the job.

**Comment by MatShir** [comment]
@PierreRambaud could you test it before we release the new build ? 😉 🙏

**Comment by matks** [comment]
I tried to find a way to detect such issues.

[Symfony does not detect this](https://symfony.com/doc/4.4/translation/lint.html) as an invalid item.
It's also valid XML I think. So the issue is somewhere else.

**Comment by eternoendless** [comment]
Fixed! https://github.com/PrestaShop/TranslationFiles/blob/5469512ed964238744002c54e272a644497c15d4/1.7/translations/1.7.8/es-ES/AdminModulesNotification.es-ES.xlf#L881

**Pull request closed without merging**
